//
//
export const FETCHING_CARS = "FETCHING_CARS";
export const FETCH_SUCCESSFUL = "FETCH_SUCCESSFUL";
export const FETCHING_CARS_FAILED = "FETCHING_CARS_FAILED";
export const SEARCHING = "SEARCHING";
export const SEARCHING_FAILED = "SEARCHING_FAILED";
export const SEARCHING_SUCCESS = "SEARCHING_SUCCESS";
export const FETCHING = "FETCHING";
export const FETCHING_SUCCESS = "FETCHING_SUCCESS";
export const FETCHING_FAILED = "FETCHING_FAILED";

