//
//
export const FETCHING_CARS = "FETCHING_CARS";
export const FETCH_SUCCESSFUL = "FETCH_SUCCESSFUL";
export const FETCHING_CARS_FAILED = "FETCHING_CARS_FAILED";
export const SEARCHING = "SEARCHING";
export const SEARCHING_FAILED = "SEARCHING_FAILED";
export const SEARCHING_SUCCESS = "SEARCHING_SUCCESS";
export const FETCHING = "FETCHING";
export const FETCHING_SUCCESS = "FETCHING_SUCCESS";
export const FETCHING_FAILED = "FETCHING_FAILED";
export const FETCHING_MAKE = "FETCHING_MAKE";
export const FETCHING_MAKE_FAILED = "FETCHING_MAKE_FAILED";
export const FETCHING_MAKE_SUCCESS = "FETCHING_MAKE_SUCCESS";
export const FETCHING_MODEL = "FETCHING_MODEL";
export const FETCHING_MODEL_FAILED = "FETCHING_MODEL_FAILED";
export const FETCHING_MODEL_SUCCESS = "FETCHING_MODEL_SUCCESS";
export const FETCHING_COLLECTION = "FETCHING_COLLECTION";
export const FETCHING_COLLECTION_FAILED = "FETCHING_COLLECTION_FAILED";
export const FETCHING_COLLECTION_SUCCESS = "FETCHING_COLLECTION_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const DETAIL = "DETAIL";
